name: "DOCS: 문서"
description: 김프런 프론트엔드의 문서 추가/수정/보완
title: "[DOCS] "
labels: ["documentation", "frontend"]
body:
  - type: textarea
    id: change
    attributes:
      label: 변경 내용
      placeholder: |
        - README에 개발 환경 설정 가이드 추가
        - STOMP WebSocket 연결 방법 문서화
        - Redux 상태 구조 다이어그램 추가
        - 컴포넌트 사용법 예제 코드 업데이트
    validations:
      required: true

  - type: textarea
    id: related
    attributes:
      label: 관련 이슈/PR
      placeholder: #123, #456
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: 체크리스트
      options:
        - label: 최신 코드와 일치 확인
        - label: 스크린샷/예시 코드 최신화
        - label: 환경 변수 및 설정 정보 확인
        - label: TypeScript 타입 정의 확인
