// 클라이언트 환경 변수 - 빌드 시점에 번들에 포함됨
export const clientEnv = {
  LOGIN_URL: process.env.NEXT_PUBLIC_LOGIN_URL,

  // Websocket
  UPBIT_WEBSOCKET_URL: process.env.NEXT_PUBLIC_UPBIT_WEBSOCKET_URL,
  BINANCE_WEBSOCKET_URL: process.env.NEXT_PUBLIC_BINANCE_WEBSOCKET_URL,
  CHAT_WEBSOCKET_URL: process.env.NEXT_PUBLIC_CHAT_WEBSOCKET_URL,
  INFO_WEBSOCKET_URL: process.env.NEXT_PUBLIC_INFO_WEBSOCKET_URL,

  // Page
  MAIN_PAGE: process.env.NEXT_PUBLIC_MAIN_PAGE,
  COMMUNITY_PAGE: process.env.NEXT_PUBLIC_COMMUNITY_PAGE,
  STATISTICS_PAGE: process.env.NEXT_PUBLIC_STATISTICS_PAGE,
  NEWS_PAGE: process.env.NEXT_PUBLIC_NEWS_PAGE,
  PROFILE_PAGE: process.env.NEXT_PUBLIC_PROFILE_PAGE,

  // Auth
  ADMIN_URL: process.env.NEXT_PUBLIC_ADMIN_URL,
  STATUS_URL: process.env.NEXT_PUBLIC_STATUS_URL,
  LOGOUT_URL: process.env.NEXT_PUBLIC_LOGOUT_URL,

  // Google
  GOOGLE_CLIENT_ID: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID,
  GOOGLE_REDIRECT_URL: process.env.NEXT_PUBLIC_GOOGLE_REDIRECT_URL,
  GOOGLE_LOGIN_URL: process.env.NEXT_PUBLIC_GOOGLE_LOGIN_URL,

  // User
  SIGNUP_URL: process.env.NEXT_PUBLIC_SIGNUP_URL,
  VERIFY_EMAIL_URL: process.env.NEXT_PUBLIC_VERIFY_EMAIL_URL,
  SEND_VERIFICATION_CODE_EMAIL_URL:
    process.env.NEXT_PUBLIC_SEND_VERIFICATION_CODE_EMAIL_URL,
  UPDATE_NICKNAME_URL: process.env.NEXT_PUBLIC_UPDATE_NICKNAME_URL,
  USER_INFO_URL: process.env.NEXT_PUBLIC_USER_INFO_URL,
};

export const serverEnv = {
  MARKET_FIRST_NAME: process.env.NEXT_PUBLIC_MARKET_FIRST_NAME,
  MARKET_UPBIT_DATA: process.env.NEXT_PUBLIC_MARKET_UPBIT_DATA,
  MARKET_COMBINE_DATA: process.env.NEXT_PUBLIC_MARKET_COMBINE_DATA,
  DOLLAR_API_URL: process.env.NEXT_PUBLIC_DOLLAR_API_URL,
  TETHER_API_URL: process.env.NEXT_PUBLIC_TETHER_API_URL,
  CHAT_LOG_URL: process.env.NEXT_PUBLIC_CHAT_LOG_URL,
  NOTICE_URL: process.env.NEXT_PUBLIC_NOTICE_URL,

  BOARD_URL: process.env.NEXT_PUBLIC_BOARD_URL,
  ALL_POSTS_URL: process.env.NEXT_PUBLIC_ALL_POSTS_URL,
  CATEGORY_URL: process.env.NEXT_PUBLIC_CATEGORY_URL,
  COMMENT_URL: process.env.NEXT_PUBLIC_COMMENT_URL,

  MARKET_BINANCE_DATA: process.env.NEXT_PUBLIC_MARKET_BINANCE_DATA,
  MARKET_DATA: process.env.NEXT_PUBLIC_MARKET_DATA,
};
